### ISSUE TITLE
Multi-sample analysis in Banksy_py

### ISSUE THREAD

**Issue by 964612858j5** [prabhakarlab/Banksy_py#1]
Hello, I am very honored to learn to use such an excellent algorithm like Banksy, but I would like to ask if the multi-sample analysis process is available in Banksy_py? Because I couldn't seem to find a function similar to connectClusters in the R version. And I also couldn't find the pipeline for multi-sample analysis. Thank you very much!

**Comment by vipulsinghal02** [comment]
Hi @Li-ZhiD and @964612858j5, 

My sincere apologies for the late response. The function analogous to the R version's `connectClusters` is `match_labels` in the python version. It is used, for example, in the [SlideSeqv1](https://github.com/prabhakarlab/Banksy_py/blob/10770c2ad707d34e0e4c07e61ea18baacf53b121/slideseqv1_analysis.ipynb) vignette. More generally, the function itself can be found [here](https://github.com/prabhakarlab/Banksy_py/blob/10770c2ad707d34e0e4c07e61ea18baacf53b121/banksy/labels.py#L246), in case you want to use it for custom multi sample analysis. 

We have not implemented a demo of multi sample analysis on our end in the Python version. Would it be possible to use the R version for your analysis? That version has a very comprehensive documentation, so even if you are not super familiar with R syntax, you might find that you can mostly just copy the vignettes and run your analyses. 

For example, [here](https://prabhakarlab.github.io/Banksy/articles/multi-sample.html) and [here](https://prabhakarlab.github.io/Banksy/articles/batch-correction.html).

**Comment by Li-ZhiD** [comment]
Thank you! I will try the python version first.

**Comment by vipulsinghal02** [comment]
Great. I will close this for now, but feel free to reopen it if you need to.

**Comment by 964612858j5** [comment]
Thank you very much for your answer! It's very helpful to me!^_^

**Comment by Sengels24** [comment]
Thanks for creating this tool. I have got a similar question: is there are multi-sample analysis pipeline available for python? 

Essentially, we have an adata frame containing cells from various samples (the sample origin is known for each cell). I was wondering how Banksy goes about creating a spatial graph when there are multiple samples in the same adata frame. This should be done for each sample separately (Construction of the spatial Nearest-Neighbour graph), but I am not sure how to go about it.
If I look in the slideseqv1_analysis.ipynb, match_labels is not used until cell clustering?

Thank you very much!
