### ISSUE TITLE
Multi-sample analysis in R version

### ISSUE THREAD

**Issue by YikaiLou** [prabhakarlab/Banksy_py#6]
hello, your work is amazing and excellent!It's my honor to use such an useful method, and I also have the same question about the multi-samples analysis.I have seen the code of R version.But when I run it myself, I can't import the dataset.And it shows an error that> spe <- spatialLIBD::fetch_data(type = "spe", eh = ehub)
Error in inherits(ram, "try-error") || length(ram) == 0L || is.na(ram) : 
  'length = 9' in coercion to 'logical(1)'
Could you give some assistance?Thank you very much!

**Comment by jleechung** [comment]
Hi @YikaiLou, thanks for your interest in BANKSY. This looks like a RAM issue. You might be able to get help by raising an issue at https://github.com/LieberInstitute/spatialLIBD/issues instead.

**Comment by YikaiLou** [comment]
ok，thank you so much!
